projects:
  garakufrontend:
    schemaPath: amplify/backend/api/garakufrontend/build/schema.graphql
    includes:
      - src/shared/api/graphql/documents/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/shared/api/graphql/types.ts
        docsFilePath: src/shared/api/graphql/documents
        maxDepth: 4
extensions:
  amplify:
    version: 3
